const fs = require('fs');
const path = require('path');

const locales = {
  en: {
    theme_store_title: "THEME STORE", run_to_earn: "RUN-TO-EARN", r2e_desc: "Exchange your running mileage points to unlock premium native HUD skins.", free_custom_ui: "My Custom UI (Free)", upload_gallery: "Upload Gallery Video / Image", premium_neons: "Premium Neons", cyberpunk_purple: "Cyberpunk Purple", electric_blue: "Electric Blue", exclusive_pro_huds: "Exclusive Pro HUDs", marathon_elite_hud: "Marathon Elite HUD", history_title: "RUNNING HISTORY", history_subtitle: "Your past runs and route maps.", morning_5k: "Morning 5K Challenge", interval_sprints: "Interval Sprints", recovery_jog: "Recovery Jog", time_label: "TIME", view_gps_map: "View GPS Route Map",
    unlock_title: "Unlock Theme", unlock_msg: "Do you want to unlock this theme?\nCost: {{price}} M\nBalance: {{balance}} M", btn_cancel: "Cancel", btn_buy: "Unlock", unlock_success_title: "Unlocked!", unlock_success_msg: "Premium theme permanently applied.", no_mileage_title: "Not Enough Mileage", no_mileage_msg: "Run {{shortfall}}km more to unlock!", equip: "Equip", cost_m: "{{price}} M Cost",
    lang_select: "Language Settings", close_btn: "Close", weekly_goal_title: "Weekly Goal", weekly_goal_desc: "Set your target distance (km) for this week (Mon-Sun).", btn_save: "Save", voice_coach_title: "Smart Voice Coach", target_pace_summary: "Target Pace: {{m}}m {{s}}s / km", voice_coach_off: "Off (Tap to Configure)", voice_coach_settings: "Voice Coach Settings", pacemaker_active: "Enable Pace Maker", target_dist_km: "Target Distance (km)", target_time_min: "Target Time (min)", expected_pace: "Expected Pace: {{m}}m {{s}}s / km", speak_dist_event: "Guide Distance/Pace Every 1km", speak_time_event: "Guide Elapsed Time Every 5min", welcome: "READY TO RUN", progress_title: "WEEKLY PROGRESS", kilometers: "KILOMETERS", runs: "RUNS", avg_pace: "AVG PACE", mode_outdoor: "OUTDOOR RUN", mode_indoor: "TREADMILL", theme: "THEMES", builder: "BUILDER", start_run: "START RUN",
    sample_coach: "Great pace. Let's keep this up until the end!", sample_uncle: "Oh, you're running well! Nice day today, let's take it easy~", sample_student: "Wow, you're really fast! I won't lose either, let's go!", sample_sister: "Don't push too hard, focus on your breathing. You can do it!", sample_drill: "Fix your posture! Push past your limits!"
  },
  ko: {
    theme_store_title: "테마 상점", run_to_earn: "런-투-언", r2e_desc: "누적 마일리지로 프리미엄 스킨을 해금하세요.", free_custom_ui: "나만의 UI (무료)", upload_gallery: "갤러리 영상 / 사진 업로드", premium_neons: "프리미엄 네온", cyberpunk_purple: "사이버펑크 퍼플", electric_blue: "일렉트릭 블루", exclusive_pro_huds: "최고급 프로 HUD", marathon_elite_hud: "마라톤 엘리트 팩", history_title: "러닝 기록", history_subtitle: "지난 러닝 기록과 이동 경로를 확인하세요.", morning_5k: "아침 5K 챌린지", interval_sprints: "전력 질주 인터벌", recovery_jog: "리커버리 조깅", time_label: "소요 시간", view_gps_map: "GPS 경로 지도 보기",
    unlock_title: "테마 잠금 해제", unlock_msg: "이 테마를 해제하시겠습니까?\n필요 마일리지: {{price}} M\n현재 보유: {{balance}} M", btn_cancel: "취소", btn_buy: "구입하기", unlock_success_title: "잠금 해제 성공!", unlock_success_msg: "새로운 프리미엄 테마가 영구적으로 적용되었습니다.", no_mileage_title: "마일리지 부족", no_mileage_msg: "달린 거리가 부족합니다.\n앞으로 {{shortfall}}km를 더 달리고 오세요!", equip: "착용하기", cost_m: "{{price}} M 비용",
    lang_select: "언어 설정 (Language)", close_btn: "닫기", weekly_goal_title: "주간 목표 설정", weekly_goal_desc: "이번 주(월~일) 달성하고 싶은 거리(km)를 설정하세요.", btn_save: "저장", voice_coach_title: "스마트 음성 코치", target_pace_summary: "목표 페이스: 1km당 {{m}}분 {{s}}초", voice_coach_off: "꺼짐 (터치하여 설정)", voice_coach_settings: "스마트 음성 코치 설정", pacemaker_active: "페이스 메이커 활성화", target_dist_km: "목표 거리 (km)", target_time_min: "목표 시간 (분)", expected_pace: "예상 페이스: 1km당 {{m}}분 {{s}}초", speak_dist_event: "매 1km마다 거리/페이스 안내", speak_time_event: "매 5분마다 경과 시간 안내", welcome: "러닝 준비 완료", progress_title: "이번 주 달성 기록", kilometers: "누적 거리 (KM)", runs: "러닝 횟수", avg_pace: "평균 페이스", mode_outdoor: "야외 러닝 (GPS)", mode_indoor: "트레드밀 (영상)", theme: "테마 상점", builder: "프로그램 조립", start_run: "러닝 시작하기",
    sample_coach: "페이스가 좋습니다. 이대로 끝까지 가봅시다!", sample_uncle: "아이고 잘 뛰네! 오늘 날씨도 좋은데 천천히 가자고~", sample_student: "와, 진짜 빠르신데요? 저도 질 수 없죠, 파이팅!", sample_sister: "무리하지 말고 호흡에 집중해 봐요. 할 수 있어요!", sample_drill: "자세 똑바로 안 합니까! 한계에 도전하십시오!"
  },
  zh: {
    theme_store_title: "主题商店", run_to_earn: "边跑边赚", r2e_desc: "用您的跑步里程兑换高级皮肤。", free_custom_ui: "自定义UI (免费)", upload_gallery: "上传画廊视频/图片", premium_neons: "高级霓虹", cyberpunk_purple: "赛博紫", electric_blue: "电光蓝", exclusive_pro_huds: "专用高级HUD", marathon_elite_hud: "马拉松精英包", history_title: "跑步历史", history_subtitle: "您过去的路线图。", morning_5k: "5K跑", interval_sprints: "间歇冲刺", recovery_jog: "恢复慢跑", time_label: "耗时", view_gps_map: "查看GPS地图",
    unlock_title: "解锁主题", unlock_msg: "你想解锁这个主题吗？\n花费: {{price}} M\n余额: {{balance}} M", btn_cancel: "取消", btn_buy: "购买", unlock_success_title: "解锁成功！", unlock_success_msg: "高级主题已永久应用。", no_mileage_title: "里程不足", no_mileage_msg: "再跑 {{shortfall}}km 即可解锁！", equip: "装备", cost_m: "{{price}} M 花费",
    lang_select: "语言选择", close_btn: "关闭", weekly_goal_title: "每周目标", weekly_goal_desc: "设定本周（周一至周日）目标距离（公里）。", btn_save: "保存", voice_coach_title: "智能语音教练", target_pace_summary: "目标配速: {{m}}分 {{s}}秒 / 公里", voice_coach_off: "关闭（点击设置）", voice_coach_settings: "语音教练设置", pacemaker_active: "启用配速功能", target_dist_km: "目标距离 (公里)", target_time_min: "目标时间 (分钟)", expected_pace: "预计配速: {{m}}分 {{s}}秒 / 公里", speak_dist_event: "每公里语音播报距离/配速", speak_time_event: "每5分钟播报经过时间", welcome: "准备开跑", progress_title: "本周进度", kilometers: "公里", runs: "次数", avg_pace: "平均配速", mode_outdoor: "户外跑 (GPS)", mode_indoor: "跑步机 (视频)", theme: "主题商店", builder: "程序构建器", start_run: "开始跑步",
    sample_coach: "配速不错。继续保持到最后！", sample_uncle: "哎呀，跑得真好！今天天气也不错，慢慢来吧~", sample_student: "哇，你跑得真快！我也不能输，加油！", sample_sister: "别勉强，集中注意力在呼吸上。你能行的！", sample_drill: "姿势端正点！挑战你的极限！"
  },
  ja: {
    theme_store_title: "テーマストア", run_to_earn: "走って稼ぐ", r2e_desc: "走行距離をプレミアムスキンと交換。", free_custom_ui: "カスタムUI (無料)", upload_gallery: "ギャラリーからアップロード", premium_neons: "プレミアムネオン", cyberpunk_purple: "サイバーパンク紫", electric_blue: "エレクトリックブルー", exclusive_pro_huds: "プロ仕様HUD", marathon_elite_hud: "マラソンエリート", history_title: "ランニング履歴", history_subtitle: "過去のランニングとルートマップ。", morning_5k: "朝の5Kラン", interval_sprints: "インターバル", recovery_jog: "リカバリージョグ", time_label: "時間", view_gps_map: "マップを表示",
    unlock_title: "テーマをロック解除", unlock_msg: "このテーマを解除しますか？\n必要マイレージ: {{price}} M\n現在の残高: {{balance}} M", btn_cancel: "キャンセル", btn_buy: "購入する", unlock_success_title: "ロック解除成功！", unlock_success_msg: "新しいプレミアムテーマが適用されました。", no_mileage_title: "マイレージ不足", no_mileage_msg: "走行距離が足りません。\nあと {{shortfall}}km 走ってください！", equip: "適用する", cost_m: "{{price}} M 費用",
    lang_select: "言語設定", close_btn: "閉じる", weekly_goal_title: "週間目標設定", weekly_goal_desc: "今週（月〜日）の目標距離（km）を設定してください。", btn_save: "保存", voice_coach_title: "スマート音声コーチ", target_pace_summary: "目標ペース: 1kmあたり {{m}}分 {{s}}秒", voice_coach_off: "オフ (タップして設定)", voice_coach_settings: "音声コーチ設定", pacemaker_active: "ペースメーカーを有効にする", target_dist_km: "目標距離 (km)", target_time_min: "目標時間 (分)", expected_pace: "予想ペース: 1kmあたり {{m}}分 {{s}}秒", speak_dist_event: "1kmごとに距離/ペースを案内", speak_time_event: "5分ごとに経過時間を案内", welcome: "走る準備はOK？", progress_title: "今週の進捗", kilometers: "キロメートル", runs: "回数", avg_pace: "平均ペース", mode_outdoor: "屋外ランニング", mode_indoor: "トレッドミル", theme: "テーマストア", builder: "プログラム作成", start_run: "ランニングを開始",
    sample_coach: "いいペースです。このまま最後まで行きましょう！", sample_uncle: "おお、いい走りだね！今日は天気もいいし、ゆっくり行こうか〜", sample_student: "うわ、本当に速いですね！私も負けませんよ、ファイト！", sample_sister: "無理しないで呼吸に集中してみて。あなたならできるよ！", sample_drill: "姿勢を正しなさい！限界に挑戦しろ！"
  },
  es: {
    theme_store_title: "TIENDA DE TEMAS", run_to_earn: "CORRE Y GANA", r2e_desc: "Canjea kilometraje para skins.", free_custom_ui: "UI Personalizada (Gratis)", upload_gallery: "Subir Imagen/Video", premium_neons: "Neones Premium", cyberpunk_purple: "Morado Cyber", electric_blue: "Azul Eléctrico", exclusive_pro_huds: "HUDs Pro", marathon_elite_hud: "Pack Élite", history_title: "HISTORIA DE CARRERAS", history_subtitle: "Tus carreras pasadas.", morning_5k: "Reto 5K", interval_sprints: "Sprints", recovery_jog: "Trote", time_label: "TIEMPO", view_gps_map: "Ver Mapa",
    unlock_title: "Desbloquear", unlock_msg: "¿Desbloquear este tema?\nCosto: {{price}} M\nSaldo: {{balance}} M", btn_cancel: "Cancelar", btn_buy: "Comprar", unlock_success_title: "¡Desbloqueado!", unlock_success_msg: "Tema premium aplicado permanentemente.", no_mileage_title: "Falta Kilometraje", no_mileage_msg: "¡Corre {{shortfall}}km más para desbloquear!", equip: "Equipar", cost_m: "Costo {{price}} M",
    lang_select: "Idioma", close_btn: "Cerrar", weekly_goal_title: "Meta Semanal", weekly_goal_desc: "Establece tu distancia objetivo (km) para esta semana.", btn_save: "Guardar", voice_coach_title: "Entrenador de Voz Inteligente", target_pace_summary: "Ritmo Objetivo: {{m}}m {{s}}s / km", voice_coach_off: "Apagado (Toca para Configurar)", voice_coach_settings: "Configuración del Entrenador de Voz", pacemaker_active: "Habilitar Marcapasos", target_dist_km: "Distancia Objetivo (km)", target_time_min: "Tiempo Objetivo (min)", expected_pace: "Ritmo Esperado: {{m}}m {{s}}s / km", speak_dist_event: "Anunciar ritmo/distancia cada 1km", speak_time_event: "Anunciar tiempo cada 5min", welcome: "LISTO PARA CORRER", progress_title: "PROGRESO SEMANAL", kilometers: "KILÓMETROS", runs: "CARRERAS", avg_pace: "RITMO MEDIO", mode_outdoor: "EXTERIORES", mode_indoor: "CINTA", theme: "TIENDA DE TEMAS", builder: "CONSTRUCTOR", start_run: "COMENZAR",
    sample_coach: "Gran ritmo. ¡Sigamos así hasta el final!", sample_uncle: "¡Oh, corres muy bien! Buen día hoy, vamos con calma~", sample_student: "¡Guau, eres muy rápido! ¡Yo tampoco perderé, vamos!", sample_sister: "No te esfuerces demasiado, concéntrate en tu respiración. ¡Tú puedes!", sample_drill: "¡Arregla tu postura! ¡Supera tus límites!"
  },
  hi: {
    theme_store_title: "थीम स्टोर", run_to_earn: "रन-टू-अर्न", r2e_desc: "प्रीमियम स्किन अनलॉक करने के लिए माइलेज पॉइंट एक्सचेंज करें।", free_custom_ui: "मेरा कस्टम यूआई", upload_gallery: "गैलरी से अपलोड", premium_neons: "प्रीमियम नियॉन", cyberpunk_purple: "साइबरपंक पर्पल", electric_blue: "इलेक्ट्रिक ब्लू", exclusive_pro_huds: "प्रो एचयूडी", marathon_elite_hud: "मैराथन एलीट पैक", history_title: "रनिंग इतिहास", history_subtitle: "आपकी पिछली दौड़ और मार्ग।", morning_5k: "सुबह की 5K", interval_sprints: "अंतराल", recovery_jog: "रिकवरी", time_label: "समय", view_gps_map: "नक्शा देखें",
    unlock_title: "अनलॉक करें", unlock_msg: "क्या आप इसे अनलॉक करना चाहते हैं?\nलागत: {{price}} M\nबैलेंस: {{balance}} M", btn_cancel: "रद्द करें", btn_buy: "खरीदें", unlock_success_title: "अनलॉक हो गया!", unlock_success_msg: "प्रीमियम थीम लागू की गई।", no_mileage_title: "माइलेज कम है", no_mileage_msg: "अनलॉक करने के लिए {{shortfall}}km और दौड़ें!", equip: "सुसज्जित करें", cost_m: "{{price}} M लागत",
    lang_select: "भाषा", close_btn: "बंद करें", weekly_goal_title: "साप्ताहिक लक्ष्य", weekly_goal_desc: "इस सप्ताह के लिए अपनी लक्षित दूरी (किमी) निर्धारित करें।", btn_save: "सहेजें", voice_coach_title: "स्मार्ट वॉइस कोच", target_pace_summary: "लक्षित गति: {{m}}m {{s}}s / किमी", voice_coach_off: "बंद (सेट करने के लिए टैप करें)", voice_coach_settings: "वॉइस कोच सेटिंग्स", pacemaker_active: "पेसमेकर सक्षम करें", target_dist_km: "लक्षित दूरी (किमी)", target_time_min: "लक्षित समय (मिनट)", expected_pace: "अपेक्षित गति: {{m}}m {{s}}s / किमी", speak_dist_event: "हर 1 किमी पर दूरी/गति बताएं", speak_time_event: "हर 5 मिनट में बीता हुआ समय बताएं", welcome: "दौड़ने के लिए तैयार", progress_title: "साप्ताहिक प्रगति", kilometers: "किलोमीटर", runs: "दौड़", avg_pace: "औसत गति", mode_outdoor: "बाहर दौड़ें", mode_indoor: "ट्रेडमिल", theme: "थीम स्टोर", builder: "बिल्डर", start_run: "शुरू करें",
    sample_coach: "बहुत अच्छी गति। अंत तक इसे बनाए रखें!", sample_uncle: "वाह, तुम अच्छा दौड़ रहे हो! आज मौसम भी अच्छा है, आराम से चलो~", sample_student: "वाह, तुम सच में तेज़ हो! मैं भी हार नहीं मानूंगा, चलो चलें!", sample_sister: "ज्यादा जोर मत लगाओ, अपनी सांसों पर ध्यान दो। तुम कर सकते हो!", sample_drill: "अपनी मुद्रा ठीक करो! अपनी सीमाओं को पार करो!"
  }
};

Object.keys(locales).forEach(lang => {
  const filePath = path.join('c:/git/running/i18n/locales', `${lang}.json`);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  data.translation = { ...data.translation, ...locales[lang] };
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
});
console.log('Update Locales Done!');
